config/routes.rb
Rails.application.routes.draw do
  resources :curriculos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/curriculo.rb
class Curriculo
  include Mongoid::Document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/curriculos_controller.rb
class CurriculosController < ApplicationController
  before_action :set_curriculo, only: [:show, :edit, :update, :destroy]

  # GET /curriculos
  # GET /curriculos.json
  def index
    @curriculos = Curriculo.all
  end

  # GET /curriculos/1
  # GET /curriculos/1.json
  def show
  end

  # GET /curriculos/new
  def new
    @curriculo = Curriculo.new
  end

  # GET /curriculos/1/edit
  def edit
  end

  # POST /curriculos
  # POST /curriculos.json
  def create
    @curriculo = Curriculo.new(curriculo_params)
    @doc = File.open("blossom.xml") { |f| Nokogiri::XML(f) }
    respond_to do |format|
      if @curriculo.save
        format.html { redirect_to @curriculo, notice: 'Curriculo was successfully created.' }
        format.json { render :show, status: :created, location: @curriculo }
      else
        format.html { render :new }
        format.json { render json: @curriculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curriculos/1
  # PATCH/PUT /curriculos/1.json
  def update
    respond_to do |format|
      if @curriculo.update(curriculo_params)
        format.html { redirect_to @curriculo, notice: 'Curriculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @curriculo }
      else
        format.html { render :edit }
        format.json { render json: @curriculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curriculos/1
  # DELETE /curriculos/1.json
  def destroy
    @curriculo.destroy
    respond_to do |format|
      format.html { redirect_to curriculos_url, notice: 'Curriculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curriculo
      @curriculo = Curriculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curriculo_params
      params.fetch(:curriculo, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/curriculos_helper.rb
module CurriculosHelper
end

app/views/curriculos/_form.html.erb
<%= form_with(model: curriculo, local: true) do |form| %>
  <% if curriculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curriculo.errors.count, "error") %> prohibited this curriculo from being saved:</h2>

      <ul>
      <% curriculo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/curriculos/edit.html.erb
<h1>Editing Curriculo</h1>

<%= render 'form', curriculo: @curriculo %>

<%= link_to 'Show', @curriculo %> |
<%= link_to 'Back', curriculos_path %>

app/views/curriculos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Curriculos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3">NOME</th>
      <th colspan="3">PLATAFORMA</th>
      <th colspan="3">QUANTIDADE DE ARTIGOS</th>
    </tr>
  </thead>

  <tbody>
    <% @curriculos.each do |curriculo| %>
      <tr>
        <td><%= link_to 'Show', curriculo %></td>
        <td><%= link_to 'Edit', edit_curriculo_path(curriculo) %></td>
        <td><%= link_to 'Destroy', curriculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'IMPORTAR E CADASTRAR CURRÍCULO', new_curriculo_path %>

app/views/curriculos/new.html.erb
<h1>IMPORTAR E CADASTRAR CURRÍCULO </h1>

<%= render 'form', curriculo: @curriculo %>

<%= link_to 'Back', curriculos_path %>

app/views/curriculos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_curriculo_path(@curriculo) %> |
<%= link_to 'Back', curriculos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>